### PR TITLE
Hf/performance test fixing

### LINKED ISSUE #337: The Performance Configuration no longer works

### PR DESCRIPTION
**Pull request by Skratzy**
fixes #337

### CODE REVIEW

File: SPLASH/src/game/states/GameState.cpp [hunk 1]
```diff
@@ -1039,13 +1041,18 @@ void GameState::createLevel(Shader* shader, Model* boundingBoxModel) {
...
-		float spawnOffsetZ = 13.f + float(i) * 1.3f;
+		Logger::Log("Adding performance test player.");
+		float spawnOffsetX = 43.f + float(i) * 2.f;
+		float spawnOffsetZ = 52.f + float(i) * 1.3f;
+
 		auto e = ECS::Instance()->createEntity("Performance Test Entity " + std::to_string(i));
 
+		EntityFactory::CreatePerformancePlayer(e, i, glm::vec3(spawnOffsetX, -0.9f, spawnOffsetZ));
+
+		/*
```
Comment (viktor4006094) [inline SPLASH/src/game/states/GameState.cpp]: Old commented out code should probably be removed

File: Sail/src/Sail/entities/systems/Gameplay/GunSystem.cpp [hunk 2]
```diff
@@ -87,13 +86,15 @@ void GunSystem::fireGun(Entity* e, GunComponent* gun) {
 	// ( Same logic for the sounds being played later on in this update function ) 
 	EntityFactory::CreateProjectile(gun->position, gun->direction * gun->projectileSpeed, true);
 
+//#ifndef _PERFORMANCE_TEST
```
Comment (viktor4006094) [inline Sail/src/Sail/entities/systems/Gameplay/GunSystem.cpp]: remove commented out `#ifndef` since it's no longer needed
