### PR TITLE
U414/t444 collision system

### LINKED ISSUE #376: Performance test players crash on candle hit
Simply do not run into the other players when performance testing, won't look into this issue

### PR DESCRIPTION
**Pull request by viktor4006094**
Multithreaded the collision system.
To make it threadsafe changes to `Transform`'s `getMatrix` and `BoundingBox`'s `getCorners` were needed so those functions have had their names changed to clarify what it is that they do.

Also fixed #376 to make testing easier.

Use commit 7bbef3e9978674ac654e86b47e3a0c0b0a9f069c to compare it with the single threaded version by setting the `OLD_COLLISION_SYSTEM` define in `CollisionSystem.cpp`

### CODE REVIEW

File: Sail/src/Sail/entities/systems/physics/CollisionSystem.cpp [hunk 1]
```diff
@@ -24,38 +26,144 @@ void CollisionSystem::provideOctree(Octree* octree) {
...
 
+
 void CollisionSystem::update(float dt) {
-	for (auto& e : entities) {
-		auto movement = e->getComponent<MovementComponent>();
-		auto collision = e->getComponent<CollisionComponent>();
-		auto boundingBox = e->getComponent<BoundingBoxComponent>();
-		auto csc = e->getComponent<CollisionSpheresComponent>();
+	constexpr size_t NR_OF_JOBS = 16;
+	constexpr size_t lastJob = NR_OF_JOBS - 1;
```
Comment (Piratkopia13) [inline Sail/src/Sail/entities/systems/physics/CollisionSystem.cpp]: if NR_OF_JOBS is capitilized, shouldnt lastJob be as well?

File: Sail/src/Sail/entities/systems/physics/UpdateBoundingBoxSystem.cpp [hunk 2]
```diff
@@ -68,7 +68,7 @@ void UpdateBoundingBoxSystem::recalculateBoundingBoxFully(Entity* e) {
 void UpdateBoundingBoxSystem::recalculateBoundingBoxPosition(Entity* e) {
 	BoundingBoxComponent* boundingBox = e->getComponent<BoundingBoxComponent>();
 	TransformComponent* transform = e->getComponent<TransformComponent>();
-	glm::mat4 transformationMatrix = transform->getMatrix();
+	glm::mat4 transformationMatrix = transform->getMatrixWithUpdate();
 	boundingBox->getBoundingBox()->setPosition(glm::vec3(transformationMatrix[3]) + glm::vec3(0.0f, boundingBox->getBoundingBox()->getHalfSize().y, 0.0f));
 	/*transform->setTranslation(boundingBox->getBoundingBox()->getPosition() - glm::vec3(0.0f, boundingBox->getBoundingBox()->getHalfSize().y, 0.0f));
 	transform->setScale(boundingBox->getBoundingBox()->getHalfSize() * 2.0f);*/
```
Comment (Piratkopia13) [inline Sail/src/Sail/entities/systems/physics/UpdateBoundingBoxSystem.cpp]: remove outcommented code if not needed anymore

File: Sail/src/Sail/graphics/geometry/Transform.cpp [hunk 3]
```diff
@@ -259,14 +259,22 @@ glm::mat4 Transform::getMatrix() {
...
+	return m_transformMatrix;
+}
+
 
+glm::mat4 Transform::getMatrixWithoutUpdate() const {
 	return m_transformMatrix;
 }
 
 glm::mat4 Transform::getRenderMatrix(float alpha) {
 	// If data hasn't changed use the CPU side transformMatrix
```
Comment (Piratkopia13) [inline Sail/src/Sail/graphics/geometry/Transform.cpp]: should these three methods really return a mat4 copy or can they be changed to `const glm::mat4&` ?

File: Sail/src/Sail/graphics/geometry/Transform.h [hunk 4]
```diff
@@ -83,7 +83,11 @@ class Transform {
...
 	// Matrix used by collision etc.
-	glm::mat4 getMatrix();
+	void prepareMatrix();
+
+	glm::mat4 getMatrixWithUpdate();
+
+	glm::mat4 getMatrixWithoutUpdate() const;
 
 	// Matrix used to render
 	glm::mat4 getRenderMatrix(float alpha = 1.0f);
```
Comment (Piratkopia13) [inline Sail/src/Sail/graphics/geometry/Transform.h]: should these three methods really return a mat4 copy or can they be changed to `const glm::mat4&` ?

File: Physics/Octree.cpp [hunk 5]
```diff
@@ -325,27 +334,41 @@ void Octree::getIntersectionData(const glm::vec3& rayStart, const glm::vec3& ray
...
-
-					if (model && !(doSimpleIntersections && collidable->allowSimpleCollision)) {
-						//Entity has a model. Check ray against meshes
-						glm::mat4 transformMatrix;
-						if (transform) {
-							transformMatrix = transform->getMatrix();
-						}
+
+	// Early exit if ray doesn't intersect with the current node closer than the closest hit
+	if (nodeIntersectionDistance < 0.0f) {// && (nodeIntersectionDistance < outIntersectionData->closestHit || outIntersectionData->closestHit < 0.0f)) {
```
[the remark this answers is not in the document]
Comment (viktor4006094) [reply Physics/Octree.cpp]: possible future optimization according to Gustav so the commented out code will stay

File: Physics/Octree.cpp [hunk 6]
```diff
@@ -325,27 +334,41 @@ void Octree::getIntersectionData(const glm::vec3& rayStart, const glm::vec3& ray
...
+		if (currentNode->entities[i] == ignoreThis) {
+			continue;
+		}
+
+		const BoundingBox* collidableBoundingBox = currentNode->entities[i]->getComponent<BoundingBoxComponent>()->getBoundingBox();
+		glm::vec3 intersectionAxis;
+		float entityIntersectionDistance = Intersection::RayWithPaddedAabb(rayStart, rayDir, collidableBoundingBox->getPosition(), collidableBoundingBox->getHalfSize(), padding, &intersectionAxis);
+
+		// Continue if ray doesn't intersect the entity bounding box closer than the closest hit
+		if (entityIntersectionDistance < 0.0f) {// && (entityIntersectionDistance < outIntersectionData->closestHit || outIntersectionData->closestHit < 0.0f)) {
```
[the remark this answers is not in the document]
Comment (viktor4006094) [reply Physics/Octree.cpp]: possible future optimization according to Gustav so the commented out code will stay

File: SPLASH/src/game/states/GameState.cpp [hunk 7]
```diff
@@ -58,7 +58,7 @@ GameState::GameState(StateStack& stack)
 
 #ifdef _PERFORMANCE_TEST
 	// TODO: Should be used but initial yaw and pitch isn't calculated from the cams direction vector in GameInputSystem
-	m_cam.setDirection(glm::normalize(glm::vec3(0.48f, -0.16f, -0.86f)));
+	m_cam.setDirection(glm::normalize(glm::vec3(0.83f, -0.11f, 0.55f)));
```
[the remark this answers is not in the document]
Comment (viktor4006094) [reply SPLASH/src/game/states/GameState.cpp]: used it to try to change the start direction of the player but that was done elsewhere anyway.
Has been restored to previous values

File: SPLASH/src/game/states/GameState.cpp [hunk 8]
```diff
@@ -152,7 +152,7 @@ GameState::GameState(StateStack& stack)
 #ifdef _PERFORMANCE_TEST
 	populateScene(lightModel, boundingBoxModel, boundingBoxModel, shader);
 
-	m_player->getComponent<TransformComponent>()->setStartTranslation(glm::vec3(52.f, 1.f, 70.f));
+	m_player->getComponent<TransformComponent>()->setStartTranslation(glm::vec3(54.f, 1.6f, 59.f));
```
[the remark this answers is not in the document]
Comment (viktor4006094) [reply SPLASH/src/game/states/GameState.cpp]: It moves the player's spawn position in the performance test so that the impact of the multithreading was easier to see

File: Sail/src/Sail/entities/systems/physics/CollisionSystem.cpp (hunk 1 above)
Comment (viktor4006094) [reply Sail/src/Sail/entities/systems/physics/CollisionSystem.cpp]: lastJob has been capitalized now

File: Sail/src/Sail/graphics/geometry/Transform.cpp (hunk 3 above)
Comment (viktor4006094) [reply Sail/src/Sail/graphics/geometry/Transform.cpp]: has been changed to `const glm::mat4` now

File: Sail/src/Sail/graphics/geometry/Transform.h (hunk 4 above)
Comment (viktor4006094) [reply Sail/src/Sail/graphics/geometry/Transform.h]: has been changed to `const glm::mat4` now

**Comment by viktor4006094** [comment]
Requested changes have been added and latest dev has been merged into the branch

**Comment by viktor4006094** [comment]
This is now ready to be merged into dev
